channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=24.3.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==2.2.1
  - lz4==4.3.3
  - numpy==1.26.1
  - psutil==5.9.1
  - scikit-learn==1.3.0
  - scipy==1.14.1
name: mlflow-env
